### ISSUE TITLE
Solution for tag-6 and tag-7 do not work.

### ISSUE THREAD

**Issue by m00se333** [learn-co-curriculum/css-graffiti-override#2]
Your code:
<img width="461" alt="screen shot 2015-12-28 at 4 03 07 pm" src="https://cloud.githubusercontent.com/assets/14082893/12027515/83ecd3fa-ad7c-11e5-92e3-f0f92a6b6534.png">

My code: 
<img width="549" alt="screen shot 2015-12-28 at 4 03 46 pm" src="https://cloud.githubusercontent.com/assets/14082893/12027520/9c3d3076-ad7c-11e5-9840-56bc15992a74.png">

My `index.html`:
<img width="1043" alt="screen shot 2015-12-28 at 4 04 31 pm" src="https://cloud.githubusercontent.com/assets/14082893/12027528/b780eaee-ad7c-11e5-9ac2-ac4573bbfb66.png">

I really hope that all these issues I am raising improves this curriculum.

**Comment by AnnJohn** [comment]
Assigned to @jongrover

**Comment by jongrover** [comment]
@m00se333 the solution branch code works on my screen see:
![screen shot 2015-12-29 at 12 44 06 pm](https://cloud.githubusercontent.com/assets/1154377/12038940/1d0e039e-ae2a-11e5-8da9-de9a75ca9d5b.png)
![screen shot 2015-12-29 at 12 44 37 pm](https://cloud.githubusercontent.com/assets/1154377/12038942/2219acbc-ae2a-11e5-9b7a-7215bb7a53ff.png)

You can see the finished solution live here: http://learn-co-curriculum.github.io/css-graffiti-override/
Try validating your CSS in case some code above tag-6 or 7 is breaking all code below for those selectors.

**Comment by jongrover** [comment]
You can see the finished solution live here: http://learn-co-curriculum.github.io/css-graffiti-override/
I will look over your Pull Request and see what the difference is between your code and mine.

**Comment by m00se333** [comment]
Hello Jonathan thanks for taking the time to look at my issue. I can't believe I'm speaking to the guy who created ZHW shoes back when that was the only HTML/CSS portion of the Flatiron curriculum (back when Learn.co was still Flatiron Prework). 

Nostalgia aside here is the code that I used to complete the lab:

```
 /* This is how I solved it last night. 

One - I moved this style sheet below or after the paint.css
Two - I accomplished this without putting div before everything. */

#wall .tag-1 {
  display: none;
}

#wall #tag-2 {
  display: none;
}
/* div id    class class */
/* a class of "slick wicked" is really two classes */
#wall #tag-3.slick.wicked {
  display: none;
}

#wall .parent #tag-4 {
  display: none;
}
/* child combiner */
/* selects the child div of .parent */
#wall .parent > div {
  display: none;
} 


/* I needed to move around the links to the style sheet */
#wall .parent > div #tag-6 {
  display: none; 
}

#wall * { 
  display: none;
}
```

As you can see I left two comments in the first few lines of my code. 

The first was suggested to me when I was seeking help on Stackoverflow, a few of the comments people made were that I needed to put the link to the cleanup.css **after** the paint.css link. I'm not sure if that is considered breaking the rules of this lab but I thought it was a good point.

The second comment I was hoping you could help me out with. I'd like to know how necessary it is to have syntax with HTML elements like `body` and `div` proceeding selectors in CSS. I'd like to compare the solution code for #tag-6.
Yours:

```
body div#wall div.parent div:last-child div#tag-6
```

Mine:

```
#wall .parent > div #tag-6
```

Both work, yet I want to know why `div` needs to be used to such an extent because I don't think the way I solved this lab is the "right" way.

If you have the time I'd really appreciate an explanation of your method. I've been teaching myself how to code for the past 4 months with Flatiron/Learn/Stackoverflow's resources; however, having an actual person talk me through an explanation of what I'm doing is far more beneficial to how I learn.

Happy New Year,

Maurice
