### ISSUE TITLE
tag-6 cannot be more specified than what is provided in paint.css

### ISSUE THREAD

**Issue by williamhancharek** [learn-co-curriculum/css-graffiti-override#6]
from what I can tell, the paint.css selects tag-6 the same way that the cleanup.css selects it, making it impossible to be overwritten.

**Comment by sgharms** [comment]
You can make it even more specific, I promise you. Your editor might tell you you're "overqualifying" but if you're as maximally specific as possible, you can outweight paint.css's application. If you need further help, try ask a question! 💙
